server:
  port: 8087

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
    hostname: localhost

cloud:
  gateway:
    routes:
      - id: employee-service
        uri: lb://employee-service
        predicates:
          - Path=/employee/**
      - id: department-service
        uri: lb://department-service
        predicates:
          - Path=/departments/**